# Generated by Django 3.0.1 on 2021-11-20 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COVAX', '0002_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Dose_one_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 21, 10, 0)),
        ),
    ]
