# Generated by Django 3.2.9 on 2021-11-26 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COVAX', '0004_auto_20211122_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Dose_one_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 27, 8, 0)),
        ),
    ]
